# Ansible Playbook of the recipe found here: https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/microservice/gaudi/README.md
# This is a simple example of a microservice that uses the Gaudi framework to create a simple chatbot that answers questions.
# Needs to be run as root user or with sudo privileges.
---
- name: OPEA ChatQnA
  hosts: localhost
  tasks:
    - name: Install pre-requisite packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: true
    - name: Add Docker's GPG key to system
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc
    - name: Add Docker repository to apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    - name: Clone the GenAIComps repo
      git:
        repo: https://github.com/opea-project/GenAIComps.git
        dest: /opt/GenAIComps
    - name: Clone the GenAIExamples repo
      git:
        repo: https://github.com/opea-project/GenAIExamples.git
        dest: /opt/GenAIExamples
    - name: Build Embedding Image
      ansible.builtin.shell:
        cmd: |
          cd /opt/GenAIComps
          docker build -t opea/embedding-tei:latest -f comps/embeddings/langchain/docker/Dockerfile .
    - name: Build Retriever Image
      ansible.builtin.shell:
        cmd: |
          cd /opt/GenAIComps
          docker build -t opea/retriever-redis:latest -f comps/retrievers/langchain/redis/docker/Dockerfile .
    - name: Build Rerank Image
      ansible.builtin.shell:
        cmd: |
          cd /opt/GenAIComps
          docker build -t opea/reranking-tei:latest -f comps/reranks/langchain/docker/Dockerfile .
    - name: Build LLM Image
      ansible.builtin.shell:
        cmd: |
          cd /opt/GenAIComps
          docker build -t opea/llm-tgi:latest -f comps/llms/text-generation/tgi/Dockerfile .
    - name: Build Dataprep Image
      ansible.builtin.shell:
        cmd: |
          cd /opt/GenAIComps
          docker build -t opea/dataprep-redis:latest -f comps/dataprep/redis/langchain/docker/Dockerfile .
    - name: Build MegaService Docker Image
      ansible.builtin.shell:
        cmd: |
          cd /opt/GenAIExamples/ChatQnA/docker
          docker build -t opea/chatqna:latest -f Dockerfile .
    - name: Build UI Docker Image
      ansible.builtin.shell:
        cmd: |
          cd /opt/GenAIExamples/ChatQnA/docker/ui
          docker build -t opea/chatqna-ui:latest -f docker/Dockerfile .
    - name: Launch the OPEA containers
      ansible.builtin.shell:
        cmd: |
          source /etc/profile.d/opea.sh
          cd /opt/GenAIExamples/ChatQnA/docker/xeon
          docker compose -f docker_compose.yaml up -d