# Ansible Playbook automation of OPEA found here: https://github.com/opea-project/GenAIExamples/blob/main/CodeGen/README.md
# This can be used standalone or as part of a Terraform script to automate the deployment of OPEA on Intel Xeon servers. See README.md
# Needs to be run as root user or with sudo privileges.
# This is compatible with Ubuntu 
---
- name: OPEA CodeGen
  hosts: localhost
  vars:
    TAG: "v0.9"
  tasks:
    - name: Install pre-requisite packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: true
    - name: Add Docker's GPG key to system
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc
    - name: Add Docker repository to apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    - name: Clone the GenAIComps repo
      git:
        repo: https://github.com/opea-project/GenAIComps.git
        dest: /opt/GenAIComps
    - name: Clone the GenAIExamples repo at commit 06117077b0b1d1a775a9f66e89fb0afd04fd6015
      git:
        repo: https://github.com/lucasmelogithub/GenAIExamples.git #To be updated to 'opea-project' org later per Lucas Melo. Required to use new React UI on compose.yaml
        refspec: 06117077b0b1d1a775a9f66e89fb0afd04fd6015
        version: 06117077b0b1d1a775a9f66e89fb0afd04fd6015
        dest: /opt/GenAIExamples
    - name: Build React UI for OPEA
      ansible.builtin.shell:
        cmd: |
          cd /opt/GenAIExamples/CodeGen/ui
          docker build --no-cache -t opea/codegen-react-ui:v0.9 --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy -f ./docker/Dockerfile.react .    
    - name: Launch the OPEA containers
      ansible.builtin.shell:
        cmd: |
          . /etc/profile.d/opea.sh
          cd /opt/GenAIExamples/CodeGen/docker_compose/intel/cpu/xeon
          docker compose -f compose.yaml up -d
      environment:
        TAG: "{{ TAG }}"