###########################################################################
# Azure Instance configuration for Intel Trust Authority (ITA)                                     #
###########################################################################
---
- name: Setup TDX with Intel Tiber Attestation (ITA) on Ubuntu on Azure Instance
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install pre-requisite packages for ITA
      ansible.builtin.apt:
        pkg:
          - make
          - gcc
          - tpm2-tools
          - gh
        state: present
        update_cache: true

    - name: Install Go using Snap
      community.general.snap:
        name: go
        classic: yes

    - name: Update and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Clone Intel trustauthority-client repository
      git:
        repo: https://github.com/intel/trustauthority-client
        version: azure-tdx-preview
        dest: /trustauthority-client

- name: Build Intel trustauthority-cli
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Build Intel trustauthority-cli
      ansible.builtin.make:
        chdir: /trustauthority-client/tdx-cli
        target: cli
      environment:
        GOPATH: "/home/adminuser/go"
        GOMODCACHE: "/home/adminuser/go/pkg/mod"
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:/home/adminuser/go/bin"

    - name: Create config.json file
      copy:
        dest: /trustauthority-client/tdx-cli/config.json
        content: |
          {
          "trustauthority_url": "https://portal.trustauthority.intel.com",
          "trustauthority_api_url": "https://api.trustauthority.intel.com",
          "trustauthority_api_key": "{{ lookup('env', 'trustauthority_api_key') }}"
          }
        mode: '0644'
      
    #Upon successful verification, the token will be decoded and displayed in key:value pairs
    - name: Perform ITA attestation
      shell: sudo /trustauthority-client/tdx-cli/trustauthority-cli token --config config.json --no-eventlog > ITA-Token.tok
      args:
        chdir: /trustauthority-client/tdx-cli

    - name: Verify the ITA Token
      shell: sudo /trustauthority-client/tdx-cli/trustauthority-cli verify --config config.json --token $(cat ITA-Token.tok) > ITA-Verify.tok
      args:
        chdir: /trustauthority-client/tdx-cli

    #NOTE: you can cat ITA-Token.tok to verify the token