###########################################################################
# Azure Instance configuration for Intel Trust Authority (ITA)                                     #
###########################################################################
---
- name: Setup TDX with Intel Tiber Attestation (ITA) on Ubuntu on Azure Instance
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install pre-requisite packages for ITA
      ansible.builtin.apt:
        pkg:
          - make
          - gcc
          - tpm2-tools
          - gh
        state: present
        update_cache: true

    - name: Install Go using Snap
      community.general.snap:
        name: go
        classic: yes

    - name: Update and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Clone Intel trustauthority-client repository
      ansible.builtin.git:
        repo: https://github.com/intel/trustauthority-client
        version: azure-tdx-preview
        dest: /trustauthority-client

    - name: Debug environment variables
      ansible.builtin.shell: printenv
      register: env_output

    - name: Print environment variables
      ansible.builtin.debug:
        var: env_output.stdout_lines

    - name: Debug current directory
      ansible.builtin.shell: pwd
      args:
        chdir: /trustauthority-client/tdx-cli
      register: pwd_output

    - name: Print current directory
      ansible.builtin.debug:
        var: pwd_output.stdout

    - name: Build Intel trustauthority-cli
      ansible.builtin.make:
        chdir: /trustauthority-client/tdx-cli
        target: cli
      environment:
        GOPATH: "/home/adminuser/go"
        GOMODCACHE: "/home/adminuser/go/pkg/mod"
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:/home/adminuser/go/bin"

    - name: Create config.json file
      ansible.builtin.template:
        src: /tmp/config.json.j2
        dest: /trustauthority-client/tdx-cli/config.json
        mode: '0644'
 
    #Upon successful verification, the token will be decoded and displayed in key:value pairs
    - name: Perform ITA attestation
      ansible.builtin.shell: sudo /trustauthority-client/tdx-cli/trustauthority-cli token --config config.json --no-eventlog > ITA-Token.tok
      args:
        chdir: /trustauthority-client/tdx-cli

    - name: Verify the ITA Token
      ansible.builtin.shell: sudo /trustauthority-client/tdx-cli/trustauthority-cli verify --config config.json --token $(cat ITA-Token.tok) > ITA-Verify.tok
      args:
        chdir: /trustauthority-client/tdx-cli

    #NOTE: you can cat ITA-Token.tok to verify the token