###########################################################################
# Azure Instance configuration for Intel Trust Authority (ITA)            #
###########################################################################
---
- name: Setup TDX with Intel Tiber Attestation (ITA) on Ubuntu on Azure Instance
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install pre-requisite packages for ITA
      ansible.builtin.apt:
        pkg:
          - make
          - gcc
          - tpm2-tools
          - gh
        state: present
        update_cache: true

    - name: Install Go using Snap
      community.general.snap:
        name: go
        classic: yes

    - name: Update and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Clone Intel trustauthority-client repository
      ansible.builtin.git:
        repo: https://github.com/intel/trustauthority-client
        version: azure-tdx-preview
        dest: /trustauthority-client
 
  