##########################################################
# Host configuration                                     #
##########################################################
---
- name: Install pre-requisite packages
  hosts: localhost
  connection: local
  tasks:
    - name: Install pre-requisite packages
      ansible.builtin.apt:
        pkg:
          - python3
          - python3-pip
          - python-is-python3
          - net-tools
        state: present
        update_cache: true
    - name: Upgrade pip
      pip:
        name: pip
        state: latest
        executable: pip3
    - name: Install Intel Extension for PyTorch
      pip:
        name: intel_extension_for_pytorch
        state: present
        executable: pip3            
    - name: Install Intel Optimum packages
      pip:
        name: "optimum[openvino,nncf]"
        state: latest
        executable: pip3
    - name: Install Intel OpenVino
      pip:
        name: openvino
        state: present
        executable: pip3
    - name: Install diffusers
      pip:
        name: diffusers
        state: present
        executable: pip3
    - name: Install typing 
      pip:
        name: typing
        state: present
        executable: pip3
    - name: Install pathlib
      pip:
        name: pathlib
        state: present
        executable: pip3
    - name: Install flask
      pip:
        name: flask
        state: present
        executable: pip3
    - name: Install torch
      pip:
        name: torch
        state: present
        executable: pip3
    - name: Install torchvision
      pip:
        name: torchvision
        state: present
        executable: pip3
    - name: Install torchaudio version
      pip:
        name: torchaudio
        state: present
        executable: pip3
    - name: Install transformers
      pip:
        name: transformers
        state: present
        executable: pip3

######################################################################
# Stable Diffusion                                                   #
#                                                                    #
# Run 'source /usr/local/bin/run-demo.sh'                            #
#                                                                    #
######################################################################

- name: Install Stable Difussion Demo
  hosts: localhost
  connection: local
  tasks:
  - name: Clone GitHub Repository https://github.com/intel/optimized-cloud-recipes.git
    ansible.builtin.git:
      repo: https://github.com/intel/optimized-cloud-recipes.git
      dest: /usr/local/bin/optimized-cloud-recipes
      version: lmelo-sd-refactor

- name: Create script to run Stable Difussion 
  hosts: localhost
  connection: local
  vars:
    script_dest: /usr/local/bin
  tasks:
    - name: Add script to run demo to bin
      copy:
        dest: "{{ script_dest }}/run-demo.sh"
        content: |
          #!/bin/bash
          cd /usr/local/bin/optimized-cloud-recipes/recipes/ai-stable_diffusion-amx-ubuntu/
          sudo python3 intel-optimized-app.py
        mode: a+x

- name: Create script for Non-optimized Stable Difussion 
  hosts: localhost
  connection: local
  vars:
    script_dest: /usr/local/bin
  tasks:
    - name: Add script to run demo to bin
      copy:
        dest: "{{ script_dest }}/run_non_optimized_demo.sh"
        content: |
          #!/bin/bash
          cd /usr/local/bin/optimized-cloud-recipes/recipes/ai-stable_diffusion-amx-ubuntu/
          sudo python3 not-optimized-app.py
        mode: a+x


- name: Complete Installation
  hosts: localhost
  connection: local
  tasks:
    - name: Create file to demonstrate recipe completion
      copy:
        dest: "/opt/recipe-run-completed_{{ ansible_date_time.date }}.txt"
        content: |
          # Run 'source /usr/local/bin/run-demo.sh' to start the demo
          # Then open a browser and navigate to http://<VM_PLUBLIC_IP>:5000         
        mode: a+x
    - name: Run 'source /usr/local/bin/run-demo.sh' to start demo
      shell: echo "Run 'source /usr/local/bin/run-demo.sh' to start demo"
