---
- name: Install pre-requisite packages
  hosts: localhost
  connection: local
  tasks:
    - name: Install pre-requisite packages
      ansible.builtin.apt:
        pkg:
          - python3-pip
        state: present
        update_cache: true
    - name: put cmd in file
      copy:
        dest: "/var/cmd"
        content: |
          python3 -m fastchat.serve.model_worker --model-path lmsys/fastchat-t5-3b-v1.0 --device cpu --controller-address http://{{ c3_ip }}:21001 --worker-address http://{{ own_ip }}:21002 --host {{ own_ip }} --model-name xeon-3 </dev/null >/dev/null 2>&1 &
        mode: a+x

- name: Install fschat with pip
  hosts: localhost
  connection: local
  tasks:
    - name: Install fschat
      pip:
        name: fschat
        state: present
        executable: pip3
    - name: Install plotly
      pip:
        name: plotly
        state: present
        executable: pip3
    - name: Install pydantic version 1.10.10
      pip:
        name: pydantic==1.10.10
        state: present
        executable: pip3
    - name: Install Intel pytorch
      pip:
        name: intel_extension_for_pytorch
        state: present
        executable: pip3

- name: Run fastchat worker
  hosts: localhost
  connection: local
  tasks:
    - name: Start web controller shell
      shell: nohup python3 -m fastchat.serve.model_worker --model-path lmsys/fastchat-t5-3b-v1.0 --device cpu --controller-address http://{{ c3_ip }}:21001 --worker-address http://{{ own_ip }}:21002 --host {{ own_ip }} --model-name xeon-3 </dev/null >/dev/null 2>&1 & 
    
