######################################################################
# Host configuration and pre-requisites                              #
######################################################################
---
- name: Install pre-requisite packages
  hosts: localhost
  connection: local
  tasks:
    - name: Install pre-requisite packages
      ansible.builtin.apt:
        pkg:
          - python3
          - python3-pip
          - python-is-python3
          - net-tools
        state: present
        update_cache: true
    - name: Install Intel's Extension for PyTorch
      pip:
        name: intel_extension_for_pytorch
        state: present
        executable: pip3
    - name: Install Jinja2 version 3.1.2
      pip:
        name: jinja2==3.1.2
        state: present
        executable: pip3

######################################################################
# Install FastChat                                                   #
######################################################################
- name: Install Fschat
  hosts: localhost
  connection: local
  tasks:
    - name: Install fschat
      pip:
        name: fschat[model_worker,webui]==0.2.30
        state: present
        executable: pip3

######################################################################
# Copy the services files from Github to the VM                      #
######################################################################
- name: Copy FastChat services files from Github to the VM
  git: 
    repo: 
  tasks:
    - name: Copy FastChat services files from Github to the VM
      git:
        repo: https://github.com/intel/optimized-cloud-recipes/tree/main/recipes/ai-fastchat-amx-ubuntu
        dest: /etc/systemd/system
        files:
          - fastchat-web.service
          - fastchat-model.service
          - fastchat-controller.service
        checkout: wfowler-contributing

######################################################################
# Enable the services                                                #
######################################################################

# Add the fastchat-model.service to systemd
- name: Add the fastchat-model.service to systemd
  systemd:
    daemon_reload: yes
    enabled: yes
    name: fastchat-model.service
    state: started

# Add the fastchat-controller.service to systemd
- name: Add the fastchat-controller.service to systemd
  systemd:
    daemon_reload: yes
    enabled: yes
    name: fastchat-controller.service
    state: started

# Add the fastchat-web.service to systemd
- name: Add the fastchat-web.service to systemd
  systemd:
    daemon_reload: yes
    enabled: yes
    name: fastchat-web.service
    state: started