---
- name: Install pre-requisite packages
  hosts: localhost
  connection: local
  tasks:
    - name: Install pre-requisite packages
      ansible.builtin.apt:
        pkg:
          - python3-pip
        state: present
        update_cache: true

- name: Install fschat with pip
  hosts: localhost
  connection: local
  tasks:
    - name: Install fschat
      pip:
        name: fschat
        state: present
        executable: pip3
    - name: Install plotly
      pip:
        name: plotly
        state: present
        executable: pip3
    - name: Install pydantic version 1.10.10
      pip:
        name: pydantic==1.10.10
        state: present
        executable: pip3


- name: Serve Falcon on CPU 
  hosts: localhost
  connection: local
  tasks:
    - name: Start web controller shell
      shell: nohup python3 -m fastchat.serve.controller --host 0.0.0.0 </dev/null >/dev/null 2>&1 & 
    - name: Serve Falcon on CPU
      shell: sleep 10 & nohup python3 -m fastchat.serve.model_worker --model-path {{ model_path | default('lmsys/fastchat-t5-3b-v1.0') }} --device cpu --model-name {{ model_name | default('xeon_4_fastchat') }} --port 21004 --worker-address http://localhost:21004 </dev/null >/dev/null 2>&1 & 



