---
- name: Install pre-requisite packages
  hosts: localhost
  connection: local
  tasks:
    - name: Install pre-requisite packages
      ansible.builtin.apt:
        pkg:
          - python3-pip
        state: present
        update_cache: true
    - name: put cmd in file
      copy:
        dest: "/var/cmd"
        content: |
          python3 -m fastchat.serve.model_worker --model-path {{ model_path | default('lmsys/fastchat-t5-3b-v1.0') }} --device cpu --controller-address http://{{ controller_ip }}:21001 --worker-address http://{{ worker_ip }}:21002 --host {{ worker_ip }} --model-name {{ model_name | default('xeon_3_fastchat') }} </dev/null >/dev/null 2>&1 &
        mode: a+x

- name: Install fschat with pip
  hosts: localhost
  connection: local
  tasks:
    - name: Install fschat
      pip:
        name: fschat==0.2.18
        state: present
        executable: pip3
    - name: Install plotly
      pip:
        name: plotly
        state: present
        executable: pip3
    - name: Install pydantic version 1.10.10
      pip:
        name: pydantic==1.10.10
        state: present
        executable: pip3
    - name: Install Intel pytorch
      pip:
        name: intel_extension_for_pytorch
        state: present
        executable: pip3

- name: Run fastchat worker
  hosts: localhost
  connection: local
  tasks:
    - name: Start worker
      shell: nohup python3 -m fastchat.serve.model_worker --model-path {{ model_path | default('lmsys/fastchat-t5-3b-v1.0') }} --device cpu --controller-address http://{{ controller_ip }}:21001 --worker-address http://{{ worker_ip }}:21002 --host {{ worker_ip }} --model-name {{ model_name | default('xeon_3_fastchat') }} </dev/null >/dev/null 2>&1 &
    
